apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db
  template:
    metadata: 
      labels:
        project: roboshop
        component: rabbitmq
        tier: db
  spec:
    - name: rabbitmq
      iamge: rabbitmq:3
      imagePullPolicy: Always
      env:
      - name: RABBITMQ_DEFAULT_USER
        value: roboshop
      - name: RABBITMQ_DEFAULT_PASS
        value: roboshop123
      readinessProbe:
        tcpSocket:
          port: 5672
        initialDelaySeconds: 15
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 5672
        initialDelaySeconds: 20
        periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port
