apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    componeet: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: lavanyaesw/momgodb:v1
          readinessProbe:
            tcpSocket:
              port: 27017
            intialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 27027
            initialDelaySrconds: 15
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    componeet: mongodb
    tier: db
  ports:
    - protocol: TCP  
      port: 27017
      targetPort: 27017